name: GitHub Actions

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-and-deploy:

    name: Build and Deploy 
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Setup Node.js latest
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install npm dependencies
      run: npm install

    - name: Build prod project
      run: npm run build:ghpages

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs